---
- name: Converge
  hosts: all
  become: true
  roles:
    # Tests the current role regardless of its directory name
    # https://github.com/ansible/molecule/issues/1567
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
